server:
  port: 8080
  servlet:
    context-path: /bootcamp
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://cywvisthgupnhx:de1cb702045b8f5b5c6a7d7a0cc76f2f4a58febb4bdd00b6084a64db87ac1ffa@ec2-52-0-114-209.compute-1.amazonaws.com:5432/d2nr98a4vna46d
    username: cywvisthgupnhx
    password: de1cb702045b8f5b5c6a7d7a0cc76f2f4a58febb4bdd00b6084a64db87ac1ffa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
